### ISSUE TITLE
Is it available in C language other than cpp?

### ISSUE THREAD

**Issue by qwer0123456** [Oxygen1a1/oxgenPdb#1]
I want to include it in the cheat engine kernel driver source

Is it available in C language?
(cheat engine source C language)

nice feature code

**Comment by Oxygen1a1** [comment]
glad to see It's helpful to you, but I've used many C++ features in this library, such as STL, move semantics, smart pointers, and templates. Perhaps you can compile your C project with a C++ compiler, but you might need to make some modifications
