### ISSUE TITLE
Improvement of Windows Version Update File Check

### ISSUE THREAD

**Issue by qwer0123456** [Oxygen1a1/oxgenPdb#2]
1. windows10 19044 C:\Windows\Temp\ntkrnlmp.pdb download
2. ntkrnlmp.pdb file check symbol load
3. but windows10 19045 update
4. 19045 old ntkrnlmp.pdb file load -> offset diff -> bsod

p->FFFFF8032B1F9620 p2->FFFFF8032BA1E060 o->232  ->19044
p->FFFFF8032B1F6F40 p2->FFFFF8032BA1E070 o->232  ->19045

Windows updates, it is essential to check for discrepancies between the pdb files and the current Windows version in the folder. Failure to do so may result in a blue screen error

**Comment by Oxygen1a1** [comment]
yes,you are right,It is important to check the MD5 of the PDB file
