### ISSUE TITLE
遇到2个问题，想请教下

### ISSUE THREAD

**Issue by huhu1208hu** [Oxygen1a1/oxgenPdb#4]
1.自测过程中：虚拟机可以成功解析符号地址、偏移，但是真机获取到的均为0，不知是否与系统版本相关（虚拟机：1909 18363.418；真机：21H2 19044.2728）？
2.自测过程中：尝试解析win32kfull.sys，但在init阶段必蓝屏；

**Comment by Oxygen1a1** [comment]
bug,暂时没精力修复
